--- #YAML:1.0
name:                CGI-Application-Plugin-CompressGzip
version:             1.00
abstract:            Add gzip compression to CGI::Application
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    CGI::Application:              3.21
    CGI::Compress::Gzip:           0.19
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Rhesa Rozendaal <rhesa@cpan.org>
