# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Application-Plugin-CompressGzip
version:      0.03
version_from: lib/CGI/Application/Plugin/CompressGzip.pm
installdirs:  site
requires:
    CGI::Application:              3.21
    CGI::Compress::Gzip:           0.19

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
